### ISSUE TITLE
Predictions don't fit the image

### ISSUE THREAD

**Issue by ningelschlingel** [Qengineering/Hand-Pose-ncnn-Raspberry-Pi-4#3]
I followed the installation steps and got the code to work.
But without changing a single line and therefore still using the example hand.jpg image,
the predictions don't seem to fit:

![IMG_6346](https://user-images.githubusercontent.com/52713123/218112008-d3bf0e68-f5fe-417f-880c-d1214f3c5dee.jpg)

Is this a known issue? Doesn't look like a scaling issue

**Comment by Qengineering** [comment]
Indeed, it's a known issue. I don't have a solution for it so far.
The cause is in the latest version of ncnn framework. Apparently something has changed so it doesn't give the same output as before when it comes to finger position.
The only way I got it working was to install an older version of ncnn.

`git clone -b 20220420 --depth=1 https://github.com/Tencent/ncnn.git`

BTW, pressing <Print Scrn> will take a snapshot of your Raspberry Pi desktop and stores it in the home/pi directory.

**Comment by ningelschlingel** [comment]
Alright, thanks again!
